<?php if(!empty($message)): ?>
<?= "<span class='msginfo'>".$message."</span>" ?>
<?php endif; ?>

<section id="formulaire-connection">
    <!-- zone de connexion -->
<h1><i class="fas fa-user"></i> Espace Membres</h1>   
    
	<form action="index.php?action=login" method="POST">
                
        <label for="email"><i class="far fa-envelope"></i>Email:</label>
        <input id="email" type="email" placeholder="Entrer votre identifiant" name="mail" required>

        <label for="password"><i class="fas fa-lock"></i>Mot de passe:</label>
        <input id="password" type="password" placeholder="Entrer le mot de passe" name="password" required>

        <input type="submit" id='submit' value='Se connecter' >
        
    </form>
    <a href="index.php?action=creer_compte">Creer un compte</a>
</section>
