<?php if(!empty($message)): ?>
<?= $message ?>
<?php endif; ?>

<section id="edition-profil">

<h1><i class="fas fa-user"></i> Modifier mon compte</h1>   
    
	<form action="index.php?action=profil" method="POST" enctype="multipart/form-data">
        
        <img src="<?= $profil['avatar'] ?>" alt="avatar de <?= htmlspecialchars($profil['user_login']) ?>">
        
        <label for="pseudo"><b><i class="far fa-envelope"></i>Pseudo :</b></label>
        <input id="pseudo" type="text" placeholder="Entrer votre pseudo" value="<?= htmlspecialchars($profil['user_login']) ?>" name="pseudo" required>

        <label for="password"><b><i class="fas fa-lock"></i>Mot de passe:</b></label>
        <input id="password" type="password" placeholder="Entrer le mot de passe" value="" name="password">

        <label for="password-bis"><b><i class="fas fa-lock"></i>Re-saisir votre Mot de passe:</b></label>
        <input id="password-bis" type="password" placeholder="Entrer le mot de passe" value="" name="password-bis">

		
		<label for="email"><b><i class="fas fa-lock"></i>Adresse email :</b></label>
        <input id="email" type="text" placeholder="Entrer votre adresse email" value="<?= htmlspecialchars($profil['user_email']) ?>" name="email" required>

        <label for="file"><b><i class="fas fa-lock"></i>Avatar :</b></label>
        <input type="file" id="file" name="avatar" accept="image/png, image/jpeg">
        <input name="avatar_bis" type="hidden" value="<?= $profil['avatar'] ?>">

        <ul>
			<li>Le fichier ne doit pas excéder 100 ko</li>
			<li>La dimension maximum de l'image est de : 90 x 90px</li>
			<li>Les formats suivants sont acceptés : jpg, png, jpeg</li>
		</ul>
        <input type="submit" id='submit' value="modifier" >
        
    </form>
</section>



