<?php if(is_connect() == TRUE): ?>
<?php header("location:index.php")?>  
<?php endif; ?>

<?php if(!empty($message)): ?>
<?= $message ?>
<?php endif; ?>

<section id="inscription">
    <!-- zone d'inscription -->
    <h1><i class="fas fa-user"></i> Creer un compte utilisateur</h1>
    
    <form action="index.php?action=creer_compte" method="POST">
              
        <label for="pseudo"><i class="far fa-envelope"></i>pseudo :</label>
        <input id="pseudo" type="text" placeholder="Entrer votre pseudo" name="pseudo" required>

        <label for="password"><i class="fas fa-lock"></i>Mot de passe:</label>
        <input id="password" type="password" placeholder="Entrer le mot de passe" name="password" required>

        <label for="password-bis"><i class="fas fa-lock"></i>Re-saisir votre Mot de passe:</label>
        <input id="password-bis" type="password" placeholder="Entrer le mot de passe" name="password-bis" required>
		
		<label for="email"><i class="fas fa-lock"></i>Adresse email :</label>
        <input id="email" type="email" placeholder="Entrer votre adresse email" name="email" required>

        <input type="submit" id='submit' value="S'inscrire" >
        
    </form>

</section>
