<nav class="navbar">
    <!-- MENU MOBILE RESPONSIVE !-->
	<div class="navbar-header">
		<button type="button" class="navbar-toggle collapsed col-md-12" data-toggle="collapse" data-target="#menu">
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
	</div>
	<!-- FIN MENU MOBILE RESPONSIVE !-->
	<!-- MENU HORIZONTALE !-->
	<div class="collapse navbar-collapse" id="menu">
		<ul class="nav navbar-nav text-uppercase">
			<li class="hidden-sm"><a href="accueil" class="dropdown-toggle"><i class="fas fa-home"></i> Accueil</a></li>
				<?= menu(); ?>
		</ul>
	</div>
</nav>