<section id="formulaire-connection-admin">
 <?php if(!empty($message)): ?>
 <span class='msginfo'><?= $message ?></span>
 <?php endif; ?>
    <!-- zone de connexion -->
<h1><i class="fas fa-user"></i> Espace Administration </h1>  
    <form action="index.php?action=login_admin" method="POST">
               
        <label for="email"><b><i class="far fa-envelope"></i>Email:</b></label>
        <input id="email" type="text" placeholder="Entrer votre identifiant" name="mail" required>

        <label for="password"><b><i class="fas fa-lock"></i>Mot de passe:</b></label>
        <input id="password" type="password" placeholder="Entrer le mot de passe" name="password" required>

        <input type="submit" id="submit" value="Se connecter" >
        
    </form>
</section>