<?php if(is_admin() == false): ?>
<?php header("location:index.php?action=administration")?>  
<?php endif; ?>   

<?php if(!empty($message)): ?>
<?= $message ?>
<?php endif; ?>

<form action="index.php?action=edit_profil_admin" method="POST" enctype="multipart/form-data">
<section id="edition-profil">
    <!-- zone de modification de profil -->
 
<h1><i class="fas fa-user"></i> Modifier mon compte</h1>
      
        <img class="avatar" src="<?= $profil['avatar'] ?>" alt="avatar de <?= htmlspecialchars($profil['nick']) ?>">
        
        <label for="pseudo"><i class="far fa-envelope"></i>Pseudo :</label>
        <input id="pseudo" type="text" placeholder="Entrer votre pseudo" value="<?= htmlspecialchars($profil['nick']) ?>" name="pseudo" required>

        <label for="password"><i class="fas fa-lock"></i>Mot de passe:</label>
        <input id="password" type="password" placeholder="Entrer le mot de passe" value="" name="password">

        <label for="password-bis"><i class="fas fa-lock"></i>Re-saisir votre Mot de passe:</label>
        <input id="password-bis" type="password" placeholder="Entrer le mot de passe" value="" name="password-bis">

		
		<label for="email"><i class="fas fa-lock"></i>Adresse email :</label>
        <input id="email" type="text" placeholder="Entrer votre adresse email" value="<?= htmlspecialchars($profil['email']) ?>" name="email" required>

        <label for="file"><i class="fas fa-lock"></i>Avatar :</label>
        <input type="file" id="file" name="avatar" accept="image/png, image/jpeg">
        <input name="avatar_bis" type="hidden" value="<?= $profil['avatar'] ?>">

        <ul>
			<li>- Le fichier ne doit pas excéder 100 ko</li>
			<li>- La dimension maximum de l'image est de : 90 x 90px</li>
			<li>- Les formats suivants sont acceptés : jpg, png, jpeg</li>
		</ul>
        <input type="submit" id='submit' value="modifier" >
        

</section>
</form>